### PR TITLE
Fixes model index pages without filters

### PR DESCRIPTION
**Pull request by smebberson**
The data grid sorting/pagination on model index pages without filters was essentially broken. These changes make them work again.

@sandytrinh, this is just a small one and read for review.

### CODE REVIEW

**Comment by sandytrinh** [comment]
Hi @smebberson 

It looks like when a filter is not present for a model, if you are currently on page 2 and changed the total records displayed per page to e.g. 50, the page refreshed and shows blank!

I was able to replicate this use on mmsUser.

**Comment by smebberson** [comment]
@sandytrinh,

Thank for your feedback. I've resolved this issue by reseting the page index whenever the page size changes. I've also made an update so that the page size controls are always rendered.

Can you please take another look?

**Comment by sandytrinh** [comment]
Tested this on my user model (without filter settings in the grid DSL) and it still not reseting the page index to one when changing the page size. Performed this test on another model and the result is the same.

**Comment by allanchau** [comment]
Pretty sure this has been fixed somewhere along the line, we should probably open a new PR if it is still an issue anyway.

**Pull request closed without merging**
