### PR TITLE
DO THIS FIRST: Async upgrade

### PR DESCRIPTION
**Pull request by allanchau**
This PR upgrades the async module in order to prevent a filterdNavigation is not a function error with the main navigation.

### Setup

- [x] Map in the master branch of Linz.

### Testing

- [x] Map in the master branch of Linz.
- [x] Log in and verify the issue.
- [x] Map in this PR.
- [x] Verify the issue is now fixed.

### CODE REVIEW

**Comment by smebberson** [comment]
@allanchau, I thought I resolved this problem myself already!

**Comment by allanchau** [comment]
Yeah I thought so too, but it seems to appear sometimes when mapping in Linz.

**Comment by smebberson** [comment]
@allanchau, But yeah, I think I solved it too but never pushed the code or something :(

**Comment by smebberson** [comment]
@allanchau, can you please just test this for me? When I ran this against `linz-development` and `linz-minitwitter-basic`, there were a few errors. I've resolved those.

To test, please temporarily roll this branch back to `621088a` and run with the above and ensuring it doesn't work very well. Then update to the latest commit and ensure everything is running smoothly.

If you can't get the `rtd` or `docs` related containers to build/run in `linz-development` just comment them out in `docker-compose.yml`.

If all goes well for you, and you add a `CHANGELOG.md` update, I'll be happy to merge this.

**Pull request merged**
