### PR TITLE
Navbar icons

### PR DESCRIPTION
**Pull request by allanchau**
Add the ability to provide icons to the navbar.

### CODE REVIEW

**Comment by allanchau** [comment]
@smebberson Ready for a review.

**Comment by smebberson** [comment]
@allanchau, could you please add a head and some basic `lorem ipsum` for the _Contact us_ and _FAQ_ pages.

**Comment by smebberson** [comment]
@allanchau, when I log in as a `member` level user, not `admin` level user - I can see the _Subscription_ navigation menu but I can't access it. Can we just remove it based on user level?

**Comment by allanchau** [comment]
@smebberson I've updated this PR with additional navigation and body tag attribute configurations.

**Pull request merged**
