### PR TITLE
Fix the count for index views

### PR DESCRIPTION
**Pull request by allanchau**
This PR fixes the list view count when listQuery filters on the results.

### CODE REVIEW

**Comment by smebberson** [comment]
@allanchau, this one is a confusing one. I only just recently made commit https://github.com/linzjs/linz/commit/fd99e561e50ebfec41986367de41fc1024e72e38 which was put in place to resolve https://github.com/aheckmann/mquery/issues/55. I'm not exactly sure how it happened, but all of a sudden any of my Linz projects where throwing a strange error relating to that. Moving the count above `listQuery` resolved it for me.

Perhaps we should split these up into two parts? Have the `listQuery` called first, then call `count()` then do the `select` and `sort` parts?

**Comment by allanchau** [comment]
@smebberson Do we even need the getCount static method? We could easily do a `totalRecords = docs.length` at ~L392 and remove a db query?

**Comment by smebberson** [comment]
@allanchau, the `getCount` static method is ultra important isn't it? It provides information about total rows for the current query and powers things such as paging in which knowing the total results is imperative. How would it work without it?

**Comment by allanchau** [comment]
@smebberson From what I can see there are currently 3 queries for the index pages:
1. Get the docs
2. Get the total records
3. Get the pageIndex (not really sure how `session.list.formData.page` is set)

Only the total records seem to use `req.linz.model.getCount`?
You would still get the total records using `docs.length` instead of creating another query.

**Comment by smebberson** [comment]
@allanchau, after our chat and the test, this looks good.

**Pull request merged**
