### PR TITLE
Fix templates for ie

### PR DESCRIPTION
**Pull request by allanchau**
This PR fixes the template tag for ie.

Signed-off-by: Allan Chau <allan.chau@icloud.com>

## Related PRs

- #188 

## Setup

- [x] Test an alwaysOn filter in IE and verify it breaks.

## Testing

- [x] Pull in this PR and verify the filter now works.

## Notes

- The related pr should be loaded in first as it requires the `addLoadEvent` function.

### CODE REVIEW

**Comment by smebberson** [comment]
@allanchau, you forgot the cache miss here...

**Comment by allanchau** [comment]
@smebberson It was updated in the previous merge? Did you want me to update it again?

**Comment by smebberson** [comment]
I think it should be updated each and every time a public JS file is changed. Yes, please update.

**Comment by allanchau** [comment]
@smebberson done now

**Pull request merged**
