### PR TITLE
Add admin home route

### PR DESCRIPTION
**Pull request by allanchau**
This PR allows the customisation of the Linz home page.

### Testing

- [x] Nothing should change by default, after passing in a custom `'admin home'` to Linz your app should break (unless that route exists).

### CODE REVIEW

**Comment by allanchau** [comment]
@smebberson You probably already know this, but you can add `?w=1` to get rid of the white space changes. https://github.com/linzjs/linz/pull/125/files?w=1

**Comment by smebberson** [comment]
@allanchau, code looks good. Could you please add something to the changelog.

**Comment by smebberson** [comment]
Hahahaha! Could you give it just a little more information... _by setting `linz.set('admin home', '/new/path')` or providing `admin home` in the `options` object.

**Comment by allanchau** [comment]
@smebberson Lol, done now.

**Pull request merged**
